---
title: "2021-03-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Makecondition

```{r makecondition}
library(reticulate)
use_condaenv("r-reticulate")

library(econR) # 經濟模型程式設計專題用
```

## Install packages

Through Conda:
```{r, eval=F}
conda_install("r-reticulate",
              packages=c("numpy", "pandas"))
```

Through PyPI:
```{r, eval=FALSE}
conda_install("r-reticulate",
              packages=c("numpy", "pandas"),
              pip = TRUE)
```


## Codes

```{python}
print("Hello, world.")
```

```{python}
class Consumer:
    # same prices
    prices = (5, 7)
    
    # difference
    def __init__(self, I, params):
        self.I = I
        self.params = params
    
    def preference(self, x):
        x1, x2 = x
        alpha, beta = self.params # heterogeneous parameters
        u = x1**alpha * x2**beta
        return u
    
    def validate_c(self, x):
        x1, x2 = x
        p_x1, p_x2 = Consumer.prices # homogeneous parameters
        if p_x1*x1 + p_x2*x2 <= self.I:
            return x
        else:
            return None

# EOF
```

```{python}
consumer11_100 = Consumer(100, (1,1))
consumer35_250 = Consumer(250, (3,5))
```

```{python}
print('homogeneous price: ' + str(consumer11_100.prices))
consumer11_100.I
consumer11_100.params

print('homogeneous price: ' + str(consumer35_250.prices))
consumer35_250.I
consumer35_250.params
```

```{python}
from numpy.random import default_rng
```

```{python}
rng_noSeed = default_rng() # no seed
```

```{python}
rns_noSeed = rng_noSeed.uniform(50, 100, size=5)
print(rns_noSeed)
```

```{python}
rng_seed = default_rng(2038) # with seed 2038
rns_seed = rng_seed.uniform(50, 100, size=5)
print(rns_seed)
```

```{python}
#1.2 practice
class demand:
    def __init__(self, params, quat):
      assert (
      type(params) is tuple
      and len(params) == 2
      and all ( [type(paramsi) is int or type(paramsi) is float for paramsi in params])
      ),"alpha、beta must be a tuple of two numbers."
      self.params = params
      self.quat   = quat
    def q(self, p):
      assert ( (type(p) is int or type(p) is float)
                and(p > 0)
             ),"price should be numeric value and greater than zero."
      alpha, beta = self.params
      q = alpha-beta*p
      if q >= 0:
        return q
      else:
        return 0

#EOF
```

```{python}
params = (10,2)
Demand = demand(params)
Demand.q(2)
```

```{python}
from numpy.random import default_rng
rng_alpha = default_rng(2038)
rng_beta = default_rng(2022)

ind_demand = [
  demand(
    (    #這個括號是為了形成tuple
    float(rng_alpha.uniform(50,100,1)),
    float(rng_beta.uniform(20,30,1))
    )
  )for i in range(500)]

#EOF
```

```{python}
sum ([ind_demand[i].q(2) for i in range(len(ind_demand))])
```

```{python}
#1.4 practice
class demand:
    def __init__(self, quat):
        self.quat = quat
    def aggregate_demand(self, x):
        assert (
          (type(x) is int or type(x) is float)
          and len(x) == 1
          ),"quat should be a number and can place one."
        self.quat = x
        overalldemand = sum ([ind_demand[i].q(x) for i in range(len(ind_demand))])
        if overalldemand >= 0:
          return overalldemand
        else:
          return 0

#EOF
```

```{python}
Demand.aggregate_demand(2)
```

